services:
  - type: web
    name: narrrfs-world-portal
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: DISCORD_CLIENT_ID
        value: your-discord-client-id
      - key: DISCORD_SECRET
        value: your-discord-secret
      - key: HELIUS_API_KEY
        value: your-helius-api-key-here

  - type: worker
    name: tor-onionpipe
    env: docker
    dockerfilePath: Dockerfile
    startCommand: |
      ./onionpipe 80~80
