<?php
// Public catalog boundary: active, valid offer presentation only. This route
// deliberately has no session requirement and never exposes user, admin, or
// purchase-history data. Purchase and mouse-context routes remain session-bound.
require_once __DIR__ . '/../config/database.php';
header('Content-Type: application/json'); header('Cache-Control: no-store');
if (($_SERVER['REQUEST_METHOD'] ?? 'GET') !== 'GET') { http_response_code(405); header('Allow: GET'); echo json_encode(['success'=>false,'error'=>'method_not_allowed']); exit; }
try { $pdo=getDatabaseConnection(); $rows=$pdo->query("SELECT o.offer_id,o.source_type,o.source_item_id,o.lp_price,o.dspoinc_price,o.stock, s.item_name AS normal_title,s.image_url AS normal_image, g.display_title AS genetic_title,g.preview_path AS genetic_image FROM tbl_mouse_lp_store_offers o LEFT JOIN tbl_store_items s ON o.source_type='normal_store' AND s.item_id=o.source_item_id AND COALESCE(s.is_active,0)=1 LEFT JOIN tbl_genetic_trait_catalog g ON o.source_type='genetic_item' AND g.catalog_id=o.source_item_id AND g.is_active=1 AND g.is_visible=1 WHERE o.is_active=1 AND o.stock>0 AND ((o.source_type='normal_store' AND s.item_id IS NOT NULL) OR (o.source_type='genetic_item' AND g.catalog_id IS NOT NULL)) ORDER BY o.offer_id ASC")->fetchAll(PDO::FETCH_ASSOC); $offers=[]; foreach($rows as $row){$normal=$row['source_type']==='normal_store';$lpPrice=$row['lp_price']===null?null:(int)$row['lp_price'];$dspoincPrice=$row['dspoinc_price']===null?null:(int)$row['dspoinc_price'];$offers[]=['offer_id'=>(int)$row['offer_id'],'source_type'=>$row['source_type'],'item_title'=>$normal?$row['normal_title']:$row['genetic_title'],'image_url'=>trim((string)($normal?$row['normal_image']:$row['genetic_image']))?:null,'lp_price'=>$lpPrice,'dspoinc_price'=>$dspoincPrice,'stock'=>(int)$row['stock'],'lp_purchase_enabled'=>$lpPrice!==null && $lpPrice>0,'dspoinc_purchase_enabled'=>$dspoincPrice!==null && $dspoincPrice>0];} echo json_encode(['success'=>true,'offers'=>$offers]); }
catch(Throwable $e){error_log('Mouse LP Store offers: '.$e->getMessage());http_response_code(503);echo json_encode(['success'=>false,'error'=>'offers_unavailable']);}
