<?php
/**
 * Security Crawler API - Professional Security Testing System
 * 
 * Features:
 * - Smart URL filtering (static assets, external domains)
 * - Web crawler with source code extraction
 * - Security vulnerability detection
 * - Brute force testing capabilities
 * - Local testing environment support
 * 
 * Created: September 29, 2025
 * Status: Local Testing Phase
 */

header('Content-Type: application/json');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: POST, GET, OPTIONS');
header('Access-Control-Allow-Headers: Content-Type');

// Handle preflight requests
if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    http_response_code(200);
    exit();
}

// Database connection
function getSQLite3Connection() {
    $dbPath = __DIR__ . '/../../db/narrrf_world.sqlite';
    if (!file_exists($dbPath)) {
        throw new Exception("Database file not found: $dbPath");
    }
    return new SQLite3($dbPath);
}

// Function to create bug report from security finding
function createBugReportFromSecurityFinding($db, $finding, $targetUrl, $crawlId, $findingId) {
    // Map security severity to bug priority
    $priorityMap = [
        'critical' => 1, // Critical
        'high' => 2,     // High
        'medium' => 3,   // Medium
        'low' => 4       // Low
    ];
    
    $priorityId = $priorityMap[$finding['severity']] ?? 3; // Default to Medium
    
    // Create bug report title
    $title = "Security Finding: " . ucfirst(str_replace('_', ' ', $finding['type'])) . " - " . $targetUrl;
    
    // Create detailed description
    $description = "**Security Vulnerability Detected**\n\n";
    $description .= "**Type:** " . ucfirst(str_replace('_', ' ', $finding['type'])) . "\n";
    $description .= "**Severity:** " . ucfirst($finding['severity']) . "\n";
    $description .= "**Target URL:** " . $targetUrl . "\n";
    $description .= "**Description:** " . $finding['description'] . "\n\n";
    $description .= "**Security Crawler Details:**\n";
    $description .= "- Crawl ID: " . $crawlId . "\n";
    $description .= "- Finding ID: " . $findingId . "\n";
    $description .= "- Detected: " . date('Y-m-d H:i:s') . "\n\n";
    $description .= "**Action Required:**\n";
    $description .= "Please review and address this security vulnerability as soon as possible.\n";
    $description .= "This bug report was automatically generated by the Security Crawler system.";
    
    // Insert bug report
    $stmt = $db->prepare("
        INSERT INTO tbl_bug_reports (
            discord_message_id, discord_channel_id, discord_user_id, discord_username,
            title, description, category_id, priority_id, status_id,
            attachments, created_at, updated_at
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    ");
    
    $stmt->bindValue(1, 'security_crawler_' . time() . '_' . $crawlId . '_' . $findingId); // Unique Discord message ID
    $stmt->bindValue(2, 'security_crawler'); // Discord channel ID
    $stmt->bindValue(3, 'security_crawler'); // System user ID
    $stmt->bindValue(4, 'Security Crawler System'); // System username
    $stmt->bindValue(5, $title, SQLITE3_TEXT);
    $stmt->bindValue(6, $description, SQLITE3_TEXT);
    $stmt->bindValue(7, 7); // Security category ID
    $stmt->bindValue(8, $priorityId, SQLITE3_INTEGER);
    $stmt->bindValue(9, 1); // Status: Reported
    $stmt->bindValue(10, json_encode([])); // No attachments
    $stmt->bindValue(11, date('Y-m-d H:i:s'), SQLITE3_TEXT);
    $stmt->bindValue(12, date('Y-m-d H:i:s'), SQLITE3_TEXT);
    
    $result = $stmt->execute();
    
    if ($result) {
        $bugId = $db->lastInsertRowID();
        
        // Log status change
        $statusStmt = $db->prepare("
            INSERT INTO tbl_bug_status_history (
                bug_id, new_status_id, changed_by, changed_at, change_reason
            ) VALUES (?, ?, ?, ?, ?)
        ");
        
        $statusStmt->bindValue(1, $bugId, SQLITE3_INTEGER);
        $statusStmt->bindValue(2, 1, SQLITE3_INTEGER); // Status: Reported
        $statusStmt->bindValue(3, 'security_crawler', SQLITE3_TEXT);
        $statusStmt->bindValue(4, date('Y-m-d H:i:s'), SQLITE3_TEXT);
        $statusStmt->bindValue(5, 'Automatically created from security finding', SQLITE3_TEXT);
        $statusStmt->execute();
        
        return $bugId;
    }
    
    return false;
}

// Smart URL filtering system
function isValidSecurityTarget($url) {
    // Exclude static assets
    if (preg_match('/\.(jpg|jpeg|png|gif|css|js|ico|svg|woff|woff2|ttf|eot|pdf|zip|rar|mp3|mp4|avi|mov)$/i', $url)) {
        return false;
    }
    
    // Exclude external domains
    $externalDomains = [
        'discord.com', 'discordapp.com', 'clubgg.com', 'twitter.com', 'facebook.com',
        'instagram.com', 'youtube.com', 'google.com', 'github.com', 'stackoverflow.com',
        'wikipedia.org', 'reddit.com', 'linkedin.com', 'tiktok.com', 'snapchat.com'
    ];
    
    foreach ($externalDomains as $domain) {
        if (strpos($url, $domain) !== false) {
            return false;
        }
    }
    
    // Exclude non-http protocols
    if (preg_match('/^(mailto|tel|javascript|data|ftp|file):/i', $url)) {
        return false;
    }
    
    // Focus on Render structure only (localhost for testing, narrrfs.world for production)
    if (strpos($url, 'narrrfs.world') === false && 
        strpos($url, 'localhost') === false && 
        strpos($url, '127.0.0.1') === false) {
        return false;
    }
    
    return true;
}

// Web crawler engine
function crawlUrl($url) {
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
    curl_setopt($ch, CURLOPT_TIMEOUT, 30);
    curl_setopt($ch, CURLOPT_USERAGENT, 'Narrrfs World Security Crawler 1.0');
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
    curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
    
    $response = curl_exec($ch);
    $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    $error = curl_error($ch);
    curl_close($ch);
    
    if ($error) {
        throw new Exception("CURL Error: $error");
    }
    
    if ($httpCode !== 200) {
        throw new Exception("HTTP Error: $httpCode");
    }
    
    return $response;
}

// Extract URLs from HTML source
function extractUrls($html, $baseUrl) {
    $urls = [];
    $baseHost = parse_url($baseUrl, PHP_URL_HOST);
    
    // Extract all href attributes
    preg_match_all('/href=["\']([^"\']+)["\']/i', $html, $matches);
    
    foreach ($matches[1] as $url) {
        // Convert relative URLs to absolute
        if (strpos($url, 'http') !== 0) {
            if (strpos($url, '/') === 0) {
                $url = 'http://' . $baseHost . $url;
            } else {
                $url = rtrim($baseUrl, '/') . '/' . $url;
            }
        }
        
        // Filter URLs
        if (isValidSecurityTarget($url)) {
            $urls[] = $url;
        }
    }
    
    return array_unique($urls);
}

// Enhanced security vulnerability detection with context awareness
function detectVulnerabilities($html, $url) {
    $findings = [];
    $lines = explode("\n", $html);
    
    // Safe patterns whitelist
    $safePatterns = [
        // CSS animations
        '@keyframes',
        'animation-keyframes',
        'keyframe',
        
        // External scripts
        '<script src=',
        '<script type="text/javascript"',
        
        // HTML form elements
        '<select',
        '<option',
        
        // HTTP methods in JavaScript
        'method: \'DELETE\'',
        'method: "DELETE"',
        'method: \'GET\'',
        'method: "GET"',
        'method: \'POST\'',
        'method: "POST"',
        
        // Button click handlers
        'onclick="this.',
        'onclick="window.',
        'onclick="dismiss',
        'onclick="close',
        
        // Meta tags
        'meta name="keywords"',
        'meta name="description"',
        
        // Comments
        '<!--',
        '//',
        '/*',
    ];
    
    foreach ($lines as $lineNum => $line) {
        $lineNum++; // Start from 1
        $line = trim($line);
        
        // Skip empty lines and comments
        if (empty($line) || strpos($line, '<!--') === 0 || strpos($line, '//') === 0) {
            continue;
        }
        
        // Check if line contains safe patterns
        $isSafe = false;
        foreach ($safePatterns as $pattern) {
            if (stripos($line, $pattern) !== false) {
                $isSafe = true;
                break;
            }
        }
        
        if ($isSafe) {
            continue; // Skip safe patterns
        }
        
        // Context-aware SQL injection detection
        if (preg_match('/\$_(GET|POST|REQUEST|COOKIE)\[.*\].*(SELECT|INSERT|UPDATE|DELETE)/i', $line)) {
            $findings[] = [
                'type' => 'sql_injection',
                'severity' => 'high',
                'description' => 'Potential SQL injection vulnerability in user input handling',
                'line_number' => $lineNum,
                'code_snippet' => $line,
                'context' => 'User input directly used in SQL query'
            ];
        }
        
        // Context-aware XSS detection
        if (preg_match('/echo\s+\$_(GET|POST|REQUEST|COOKIE)\[.*\]|print\s+\$_(GET|POST|REQUEST|COOKIE)\[.*\]/i', $line)) {
            $findings[] = [
                'type' => 'xss',
                'severity' => 'medium',
                'description' => 'Potential XSS vulnerability - user input directly output',
                'line_number' => $lineNum,
                'code_snippet' => $line,
                'context' => 'User input directly output without sanitization'
            ];
        }
        
        // Context-aware information disclosure
        if (preg_match('/\$_(GET|POST|REQUEST|COOKIE)\[.*\].*(password|secret|key|token|api_key|private)/i', $line)) {
            $findings[] = [
                'type' => 'information_disclosure',
                'severity' => 'medium',
                'description' => 'Potential sensitive information in user input',
                'line_number' => $lineNum,
                'code_snippet' => $line,
                'context' => 'Sensitive information handling in user input'
            ];
        }
        
        // Directory traversal detection
        if (preg_match('/\$_(GET|POST|REQUEST|COOKIE)\[.*\].*(\.\.\/|\.\.\\\\|\.\.%2f|\.\.%5c)/i', $line)) {
            $findings[] = [
                'type' => 'directory_traversal',
                'severity' => 'high',
                'description' => 'Potential directory traversal vulnerability',
                'line_number' => $lineNum,
                'code_snippet' => $line,
                'context' => 'User input used in file path operations'
            ];
        }
    }
    
    return $findings;
}

// Main API handler
try {
    $method = $_SERVER['REQUEST_METHOD'];
    $input = json_decode(file_get_contents('php://input'), true);
    
    $db = getSQLite3Connection();
    
    switch ($method) {
        case 'POST':
            $action = $input['action'] ?? '';
            
            switch ($action) {
                case 'start_crawl':
                    $targetUrl = $input['target_url'] ?? '';
                    
                    if (empty($targetUrl)) {
                        throw new Exception('Target URL is required');
                    }
                    
                    if (!isValidSecurityTarget($targetUrl)) {
                        throw new Exception('Invalid target URL - filtered by security rules');
                    }
                    
                    // Insert crawl record
                    $stmt = $db->prepare("
                        INSERT INTO tbl_security_crawls 
                        (target_url, crawl_status, created_at, is_local_test) 
                        VALUES (?, 'in_progress', CURRENT_TIMESTAMP, 1)
                    ");
                    $stmt->bindValue(1, $targetUrl, SQLITE3_TEXT);
                    $stmt->execute();
                    
                    $crawlId = $db->lastInsertRowID();
                    
                    // Start crawling
                    try {
                        $html = crawlUrl($targetUrl);
                        $foundUrls = extractUrls($html, $targetUrl);
                        $vulnerabilities = detectVulnerabilities($html, $targetUrl);
                        
                        // Update crawl record
                        $stmt = $db->prepare("
                            UPDATE tbl_security_crawls 
                            SET crawl_status = 'completed', 
                                completed_at = CURRENT_TIMESTAMP,
                                source_code = ?,
                                found_urls = ?,
                                security_findings = ?
                            WHERE id = ?
                        ");
                        $stmt->bindValue(1, $html, SQLITE3_TEXT);
                        $stmt->bindValue(2, json_encode($foundUrls), SQLITE3_TEXT);
                        $stmt->bindValue(3, json_encode($vulnerabilities), SQLITE3_TEXT);
                        $stmt->bindValue(4, $crawlId, SQLITE3_INTEGER);
                        $stmt->execute();
                        
                        // Insert security findings and create bug reports
                        $bugReportsCreated = 0;
                        foreach ($vulnerabilities as $finding) {
                            // Insert security finding
                            $stmt = $db->prepare("
                                INSERT INTO tbl_security_findings 
                                (crawl_id, finding_type, severity, description, status, created_at, is_local_test, line_number, code_snippet, context) 
                                VALUES (?, ?, ?, ?, 'open', CURRENT_TIMESTAMP, 1, ?, ?, ?)
                            ");
                            $stmt->bindValue(1, $crawlId, SQLITE3_INTEGER);
                            $stmt->bindValue(2, $finding['type'], SQLITE3_TEXT);
                            $stmt->bindValue(3, $finding['severity'], SQLITE3_TEXT);
                            $stmt->bindValue(4, $finding['description'], SQLITE3_TEXT);
                            $stmt->bindValue(5, $finding['line_number'] ?? null, SQLITE3_INTEGER);
                            $stmt->bindValue(6, $finding['code_snippet'] ?? null, SQLITE3_TEXT);
                            $stmt->bindValue(7, $finding['context'] ?? null, SQLITE3_TEXT);
                            $stmt->execute();
                            
                            $findingId = $db->lastInsertRowID();
                            
                            // Create bug report for this security finding
                            if (createBugReportFromSecurityFinding($db, $finding, $targetUrl, $crawlId, $findingId)) {
                                $bugReportsCreated++;
                            }
                        }
                        
                        echo json_encode([
                            'success' => true,
                            'message' => 'Crawl completed successfully',
                            'data' => [
                                'crawl_id' => $crawlId,
                                'target_url' => $targetUrl,
                                'found_urls' => $foundUrls,
                                'vulnerabilities' => $vulnerabilities,
                                'url_count' => count($foundUrls),
                                'finding_count' => count($vulnerabilities),
                                'bug_reports_created' => $bugReportsCreated
                            ]
                        ]);
                        
                    } catch (Exception $e) {
                        // Update crawl record with error
                        $stmt = $db->prepare("
                            UPDATE tbl_security_crawls 
                            SET crawl_status = 'failed', 
                                completed_at = CURRENT_TIMESTAMP,
                                security_findings = ?
                            WHERE id = ?
                        ");
                        $stmt->bindValue(1, json_encode([['error' => $e->getMessage()]]), SQLITE3_TEXT);
                        $stmt->bindValue(2, $crawlId, SQLITE3_INTEGER);
                        $stmt->execute();
                        
                        throw $e;
                    }
                    break;
                    
                case 'get_crawls':
                    $stmt = $db->prepare("
                        SELECT * FROM tbl_security_crawls 
                        WHERE is_local_test = 1 
                        ORDER BY created_at DESC 
                        LIMIT 50
                    ");
                    $result = $stmt->execute();
                    
                    $crawls = [];
                    while ($row = $result->fetchArray(SQLITE3_ASSOC)) {
                        $crawls[] = $row;
                    }
                    
                    echo json_encode([
                        'success' => true,
                        'data' => $crawls
                    ]);
                    break;
                    
                case 'get_findings':
                    $stmt = $db->prepare("
                        SELECT sf.*, sc.target_url 
                        FROM tbl_security_findings sf
                        LEFT JOIN tbl_security_crawls sc ON sf.crawl_id = sc.id
                        WHERE sf.is_local_test = 1 
                        ORDER BY sf.created_at DESC 
                        LIMIT 100
                    ");
                    $result = $stmt->execute();
                    
                    $findings = [];
                    while ($row = $result->fetchArray(SQLITE3_ASSOC)) {
                        $findings[] = $row;
                    }
                    
                    echo json_encode([
                        'success' => true,
                        'data' => $findings
                    ]);
                    break;
                    
                default:
                    throw new Exception('Invalid action');
            }
            break;
            
        case 'GET':
            // Get system status
            $stmt = $db->prepare("SELECT COUNT(*) as total_crawls FROM tbl_security_crawls WHERE is_local_test = 1");
            $result = $stmt->execute();
            $totalCrawls = $result->fetchArray(SQLITE3_ASSOC)['total_crawls'];
            
            $stmt = $db->prepare("SELECT COUNT(*) as total_findings FROM tbl_security_findings WHERE is_local_test = 1");
            $result = $stmt->execute();
            $totalFindings = $result->fetchArray(SQLITE3_ASSOC)['total_findings'];
            
            echo json_encode([
                'success' => true,
                'data' => [
                    'total_crawls' => $totalCrawls,
                    'total_findings' => $totalFindings,
                    'status' => 'operational',
                    'environment' => 'local_testing'
                ]
            ]);
            break;
            
        default:
            throw new Exception('Method not allowed');
    }
    
} catch (Exception $e) {
    http_response_code(500);
    echo json_encode([
        'success' => false,
        'error' => $e->getMessage()
    ]);
} finally {
    if (isset($db)) {
        $db->close();
    }
}
?>
